### PR TITLE
Fixed text visibility on dark themes

### LINKED ISSUE #1: Some text is nearly unreadable
Certain dialogs (unfocused windows/subwindows, all VirtualBox text) lose all their contrast after applying the theme. I'm not sure what causes this, but it makes a several applications very hard to use.

### PR DESCRIPTION
**Pull request by ItsEthra**
Closes #1

### CODE REVIEW

**Comment by revsuine** [comment]
In favour of merging this; I've tried it out and it's improved visibility with Mocha.

Also, is there a way to fix this with KeePassXC with Mocha? This is the one instance of bad visibility I've still noticed with this PR (it's present in the base repo too).

screenshot of bad visibility in KeePassXC

**Comment by shadow-absorber** [comment]
same problem with keepassxc here

**Comment by shadow-absorber** [comment]
it is better then the old one but still problematic in keepassxc... otherwise it works just fine... running this on i3 with the gtk theme for gtk apps and this qt5ct theme for qt apps

**Comment by sgoudham** [comment]
Hi 👋,

So sorry but this PR has now been superseded by #5. It's unfortunate that this didn't get merged earlier!

**Pull request closed without merging**
